## Configuration file for 2016 election

independent_seats = {'Denison':'IND',
					 'Indi':'IND',
					 #'Fairfax':'PUP',
					 'Kennedy':'KAP',
					 'Melbourne':'GRN'}

retiring_seats = {'Chisolm':'ALP',
				  'Werriwa':'ALP',
				  'Brand':'ALP',
				  'Bruce':'ALP',
				  'Shortland':'ALP',
				  'Perth':'ALP',
				  'Fremantle':'ALP',
				  'Oxley':'ALP',
				  'Wills':'ALP',
				  'Paterson':'COA',
				  'Dunkley':'COA',
				  'Goldstein':'COA',
				  'Berowra':'COA',
				  'Boothby':'COA',
				  'Murray':'COA',
				  'Fisher':'COA',
				  'Brisbane':'COA',
				  'Groom':'COA',
				  'Maranoa':'COA',
				  'Wide Bay':'COA',
				  'Calare':'COA'}


sophomore_seats = {'Lyne':'COA',
				   'New England':'COA',
				   'Charlton':'ALP',
				   'Hotham':'ALP',
				   'Rankin':'ALP',
				   'Batman':'ALP',
				   'Kingsford Smith':'ALP',
				   'Bendigo':'ALP',
				   'Lalor':'ALP',
				   'Newcastle':'ALP',
				   'Scullin':'ALP',
				   'Capricornia':'COA',
				   'Barton':'COA',
				   'Gellibrand':'ALP',
				   'Perth':'ALP',
				   'Gilmore':'COA',
				   'Durack':'COA',
				   'Pearce':'COA',
				   'Hume':'COA',
				   'Barker':'COA',
				   'Moore':'COA',
				   'Hinkler':'COA',
				   'Fairfax':'PUP',
				   'Mallee':'COA',
				   'O\'Connor':'COA'}